package com.example.group6.dulichdoday;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.Spinner;

import com.example.group6.dulichdoday.Adapter.AdapterSpinner;
import com.example.group6.dulichdoday.Adapter.AdapterTour;
import com.example.group6.dulichdoday.Adapter.AdapterTours;
import com.example.group6.dulichdoday.Models.Tours;
import com.example.group6.dulichdoday.Models.mdSpinner;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;


/**
 * A simple {@link Fragment} subclass.
 */
public class TourFragment extends Fragment {

    // Hãng
    private ArrayList<mdSpinner> arraylistMien;
    private ArrayList<String> arrayListPrice;
    private Spinner spinnerMien;
    private AdapterTour adapterTour;
    private ArrayList<Tours> arrTour;
    private RecyclerView recyclerViewTour;
    private DatabaseReference mData;
    int posi;
    public TourFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_tour, container, false);
        //FIREBASE
        mData = FirebaseDatabase.getInstance().getReference();
        spinnerMien = (Spinner) view.findViewById(R.id.spinnerTour);
        recyclerViewTour = (RecyclerView) view.findViewById(R.id.recyclerViewTour);
        // Spinner
        arraylistMien = new ArrayList<mdSpinner>();
        arraylistMien.add(new mdSpinner(R.drawable.northpole,"Tất Cả"));
        arraylistMien.add(new mdSpinner(R.drawable.itinerary,Tours.MIEN_BAC));
        arraylistMien.add(new mdSpinner(R.drawable.itinerary,Tours.MIEN_TRUNG));
        arraylistMien.add(new mdSpinner(R.drawable.itinerary, Tours.MIEN_NAM));

        AdapterSpinner arrayAdapterMien = new AdapterSpinner(getContext(), R.layout.custom_spinner, arraylistMien);
        spinnerMien.setAdapter(arrayAdapterMien);


        // Xử lý hiển thị recycler
        LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity(), LinearLayoutManager.VERTICAL,false);
        recyclerViewTour.setHasFixedSize(true);
        recyclerViewTour.setLayoutManager(layoutManager);

        arrTour = new ArrayList<Tours>();
        /*arrTour.add(new Tours("01","kAYYWw8JvCX3pr1XlbjCvXyY8nD2","Hà Nội- Cao Nguyên","3 Ngày 2 Đêm","1.900.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/cao%20nguy%C3%AAn.jpg?alt=media&token=ce5fc913-92dd-40e0-8c3f-7615acaa82ef","Miền Bắc"));
        arrTour.add(new Tours("02","1","Hà Nội - Mộc Châu","3 Ngày 2 Đêm","200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/banchay_com1448684716_cho-phien-muong-khuong.jpg?alt=media&token=008cc4e8-66e6-4d44-a527-6bdab59682f0", "Miền Bắc"));
        arrTour.add(new Tours("03","1","Hà Nội - Sơn La","3 Ngày 2 Đêm","1.000.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/photo-1-1491635495649.jpg?alt=media&token=a0fd07ae-46ec-4480-bcd7-aa14063e0914", "Miền Bắc"));
        arrTour.add(new Tours("04","kAYYWw8JvCX3pr1XlbjCvXyY8nD2","TP.HCM - Đà Lạt","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/ph%C3%BA%20y%C3%AAn.jpg?alt=media&token=44f1d7a2-d439-4a84-85d6-8e8f50f4f399", "Miền Bắc"));
        arrTour.add(new Tours("05","1","Nha Trang - Hà Nội","7 Ngày 6 Đêm","1.700.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/ph%C3%BA%20y%C3%AAn%202.jpg?alt=media&token=c110b494-62b0-4a8a-ae0a-ca74e5df056a", "Miền Trung"));
        arrTour.add(new Tours("06","kAYYWw8JvCX3pr1XlbjCvXyY8nD2","TP.HCM - Phan Thiết","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/ph%C3%BA%20y%C3%AAn1.jpg?alt=media&token=81cd2b64-a494-402d-8b6c-1f78dbccbd85", "Miền Nam"));
        arrTour.add(new Tours("07","1","Hà Nội - TPHCM","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/pic2520.jpg?alt=media&token=8ab7a69a-6b98-456d-a49f-0c7417013342", "Miền Bắc"));
        arrTour.add(new Tours("08","1","Hà Nội - Hải Phòng","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/sapa.jpg?alt=media&token=4819b1cc-6ad1-4db5-a575-a906738f8284", "Miền Bắc"));
        arrTour.add(new Tours("09","1","Nha Trang - Cổ Thạch","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/Th%C3%A1p%20Ch%C4%83m.jpg?alt=media&token=7ab5e387-bc68-45cd-84b1-b1487f8f29bc", "Miền Trung"));
        arrTour.add(new Tours("10","kAYYWw8JvCX3pr1XlbjCvXyY8nD2","Nha Trang - Lagi","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/t%C3%A2y%20b%E1%BA%AFc.jpg?alt=media&token=6e6b154d-3ed2-4b64-905f-80e7bb54f1b4", "Miền Trung"));
        arrTour.add(new Tours("11","1","TP.HCM - Đà Nẵng","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/%C4%90%C3%A0%20N%E1%BA%B5ng.jpg?alt=media&token=3bb07b4e-2836-4cd7-8b91-679ab39548a2", "Miền Nam"));
        arrTour.add(new Tours("12","1","TP.HCM - Vũng Tàu","3 Ngày 2 Đêm","250.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/%C4%91%E1%BB%93ng%20v%C3%A2n.jpg?alt=media&token=9d8cf8cf-1288-413b-9a35-c41f182d47ca","Miền Nam"));
        arrTour.add(new Tours("13","1","Nha Trang - Lagi","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/qu%C3%AA%20tui.jpg?alt=media&token=468dbd58-5477-40ad-9f1a-96269a27e1a8","Miền Trung"));
        arrTour.add(new Tours("14","1","TP.HCM - Hà Tiên","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/m%E1%BB%99c%20ch%C3%A2u.jpg?alt=media&token=209c8f08-df02-443d-b330-687236f25289","Miền Nam"));
        arrTour.add(new Tours("15","kAYYWw8JvCX3pr1XlbjCvXyY8nD2","TP.HCM - Bàu Trắng","3 Ngày 2 Đêm","250.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img_vhl.jpg?alt=media&token=188614f9-4242-41a0-a48e-52cb859845e6","Miền Nam"));
        arrTour.add(new Tours("16","1","Hà Nội- Cao Nguyên","3 Ngày 2 Đêm","1.900.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img_nhatrang.jpg?alt=media&token=3eb90663-88cb-4572-99be-ad8950dd1024","Miền Bắc"));
        arrTour.add(new Tours("17","1","Hà Nội - Vịnh Hạ Long","3 Ngày 2 Đêm","200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img_dalat.jpg?alt=media&token=41f21021-acb3-4ecf-8d73-7839e0897eda","Miền Bắc"));
        arrTour.add(new Tours("18","kAYYWw8JvCX3pr1XlbjCvXyY8nD2","Nha Trang - Sapa","3 Ngày 2 Đêm","1.000.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img_5.jpg?alt=media&token=9a4b1774-b109-4e3b-9e3d-e41ad290b8e9","Miền Trung"));
        arrTour.add(new Tours("19","1","Nha Trang - Bình Ba","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img_4.jpg?alt=media&token=9f790523-3f52-41e0-ae08-85bee5c2b704","Miền Trung"));
        arrTour.add(new Tours("20","1","TP.HCM - Tam Đảo","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img_3.jpg?alt=media&token=87c1291a-ddda-477d-ad66-80c6e96b2e47","Miền Nam"));
        arrTour.add(new Tours("21","kAYYWw8JvCX3pr1XlbjCvXyY8nD2","Hà Nội - Lạng Sơn","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img_2.jpg?alt=media&token=9117c942-c9ca-45a9-ad0b-d3913f7c60d2","Miền Bắc"));
        arrTour.add(new Tours("22","1","Hà Nội - Quảng Bình","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/img1.jpg?alt=media&token=5b46343b-a96e-4a7c-9d26-f766c518a775","Miền Bắc"));
        arrTour.add(new Tours("23","1","Nha Trang - Mộc Châu","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/h%E1%BB%93%20g%C6%B0%C6%A1m.jpg?alt=media&token=d76e06bc-aff0-4914-ae9a-39a556f89ec2","Miền Trung"));
        arrTour.add(new Tours("24","1","Nha Trang - Lagi","3 Ngày 2 Đêm","1.200.000 đ","Ngày 01\n •\t6h45 – 7h00: Khởi hành đi Mộc Châu.\n  •\t12h30: Đến Mộc Châu Arena Village, nhận phòng và ăn trưa với các món ăn đặc sản của vùng núi Tây Bắc\n •\t14h30: Đi thăm bản của đồng bào dân tộc H’Mông tại tiểu khu Chiềng Công.\n •\t15h30: Đi tham quan xưởng chế biến chè theo phương pháp thủ công.\n •\t16h30: Về Mộc Châu Arena Village nghỉ ngơi.\n •\t19h00: Ăn tối.\n •\tSau bữa tối, tự do nghỉ ngơi, thư giãn hoặc có thể tham gia chương trình \"Hát cho nhau nghe\" tại nhà hàng của Arena. \nNgày 02\n •\t7h00: Ăn sáng.\n •\t8h00: Đi tham quan Hang Dơi.\n •\tSau khi khám phá Hang Dơi, tiếp tục hành trình thăm quan Thác Dải Yếm (Thác Nàng, thác Bản Vặt) gắn liền với câu chuyện cô gái cứu chàng trai thoát khỏi dòng nước lũ.\n •\t9h30: Đi tham quan Bản Áng (nơi sinh sống của đồng bào dân tộc Thái) và rừng thông Bản Áng.\n •\t10h15: Quay trở về chợ trung tâm thị trấn Mộc Châu để mua sản vật địa phương để làm quà\n •\t11h00: Quay về khách sạn trả phòng sau đó dùng bữa trưa\n •\t13h30: Lên xe trở về Hà Nội","https://firebasestorage.googleapis.com/v0/b/dulichdodaydemo.appspot.com/o/cong-troi-sapa.png?alt=media&token=9bf74c4e-60f4-466e-84e6-41ced6217eb5","Miền Trung"));
        mData.child(Tours.CHILD_TOURS).setValue(arrTour);*/
        loadData();
        return view;
    }

    private void loadData() {

        arrTour = new ArrayList<Tours>();
        // Set adapter
        adapterTour = new AdapterTour(arrTour,getContext());
        recyclerViewTour.setAdapter(adapterTour);
        recyclerViewTour.addOnItemTouchListener(new RecyclerView.SimpleOnItemTouchListener());
        spinnerMien.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
                arrTour.clear();
                posi = i;
                mData.child(Tours.CHILD_TOURS).addChildEventListener(new ChildEventListener() {
                    @Override
                    public void onChildAdded(DataSnapshot dataSnapshot, String s) {
                        final Tours tours = dataSnapshot.getValue(Tours.class);
                        if (posi == 0)
                        {
                            //Tours tours = dataSnapshot.getValue(Tours.class);
                            arrTour.add(new Tours(tours.getTour_ID(), tours.getAccount_ID(), tours.getTourName(), tours.getTourTime(), tours.getTourPrice(), tours.getTourDescription(), tours.getImgTour(), tours.getTenMien()));
                            //arrTour.add(new Tours(tour.getImgProduct(),tour.getCodeTour(),tour.getAddTour(),tour.getDiscripTour(),tour.getPriceTour(),tour.getTenmien(),tour.getNoidung()));
                            adapterTour.notifyDataSetChanged();
                        }
                        else if (posi == 1 && tours.getTenMien().equalsIgnoreCase(Tours.MIEN_BAC))
                        {
                            arrTour.add(new Tours(tours.getTour_ID(), tours.getAccount_ID(), tours.getTourName(), tours.getTourTime(), tours.getTourPrice(), tours.getTourDescription(), tours.getImgTour(), tours.getTenMien()));
                            //arrTour.add(new Tour(tour.getImgProduct(),tour.getCodeTour(),tour.getAddTour(),tour.getDiscripTour(),tour.getPriceTour(),tour.getTenmien(),tour.getNoidung()));
                            adapterTour.notifyDataSetChanged();
                        }else if (posi == 2 && tours.getTenMien().equalsIgnoreCase(Tours.MIEN_TRUNG)) {
                            arrTour.add(new Tours(tours.getTour_ID(), tours.getAccount_ID(), tours.getTourName(), tours.getTourTime(), tours.getTourPrice(), tours.getTourDescription(), tours.getImgTour(), tours.getTenMien()));
                            //arrTour.add(new Tour(tour.getImgProduct(),tour.getCodeTour(),tour.getAddTour(),tour.getDiscripTour(),tour.getPriceTour(),tour.getTenmien(),tour.getNoidung()));
                            adapterTour.notifyDataSetChanged();
                        }else if (posi == 3 && tours.getTenMien().equalsIgnoreCase(Tours.MIEN_NAM)) {
                            arrTour.add(new Tours(tours.getTour_ID(), tours.getAccount_ID(), tours.getTourName(), tours.getTourTime(), tours.getTourPrice(), tours.getTourDescription(), tours.getImgTour(), tours.getTenMien()));
                            //arrTour.add(new Tour(tour.getImgProduct(),tour.getCodeTour(),tour.getAddTour(),tour.getDiscripTour(),tour.getPriceTour(),tour.getTenmien(),tour.getNoidung()));
                            adapterTour.notifyDataSetChanged();
                        }
                    }

                    @Override
                    public void onChildChanged(DataSnapshot dataSnapshot, String s) {

                    }

                    @Override
                    public void onChildRemoved(DataSnapshot dataSnapshot) {

                    }

                    @Override
                    public void onChildMoved(DataSnapshot dataSnapshot, String s) {

                    }

                    @Override
                    public void onCancelled(DatabaseError databaseError) {

                    }
                });
            }

            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
        });
    }

}
